# Generated by Django 5.2.3 on 2025-09-12 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='tipo_cuenta',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('medico', 'Medico'), ('administrador', 'Administrador')], default='cliente', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='telefono',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{7, 11}$', 'Ingrese un número válido de 7 a 11 dígitos.')]),
        ),
    ]
