# Generated by Django 5.2.3 on 2025-11-29 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariotrabajo',
            name='lugar',
            field=models.ForeignKey(help_text='Debe ingresar un lugar de trabajo previamente.', on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='cuenta.lugartrabajo'),
        ),
    ]
