# Generated by Django 5.2.3 on 2025-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_usuariopersonalizado_tipo_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo_cuenta',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('medico', 'Medico'), ('administrador', 'Administrador')], default='Cliente', max_length=13),
        ),
    ]
