# Generated by Django 5.1.1 on 2025-09-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_alter_usuariopersonalizado_tipo_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='telefono',
            field=models.CharField(max_length=11),
        ),
    ]
