# Generated by Django 5.2.3 on 2025-11-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_alter_horariotrabajo_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariotrabajo',
            name='tiempo_turno',
            field=models.DurationField(help_text='Duración entre turnos. eeEjemplo: 00:20:00 para 20 minutos'),
        ),
    ]
