# Generated by Django 5.2.3 on 2025-11-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_remove_consulta_paciente_consulta_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='HistoriaClinica',
        ),
    ]
