# Generated by Django 5.2.3 on 2025-11-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_remove_historiaclinica_usuario_delete_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariotrabajo',
            name='tiempo_turno',
            field=models.TimeField(help_text='Duración entre turnos. Ejemplo: 00:20:00 para 20 minutos'),
        ),
    ]
