# Generated by Django 5.1.1 on 2025-09-16 18:00

import cuenta.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_alter_usuariopersonalizado_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='foto_dni',
            field=models.ImageField(null=True, upload_to=cuenta.models.ruta_dni),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo_cuenta',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('medico', 'Medico')], default='Cliente', max_length=13),
        ),
        migrations.CreateModel(
            name='Dni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
