# Generated by Django 5.2.6 on 2025-11-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_medico_localidad'),
        ('cuenta', '0004_remove_historiaclinica_usuario_delete_consulta_and_more'),
    ]

    operations = [
    ]
