# Generated by Django 5.2.6 on 2025-09-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_usuariopersonalizado_foto_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='num_dni',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='telefono',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
