# Generated by Django 5.2.3 on 2025-11-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_alter_horariotrabajo_tiempo_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariotrabajo',
            name='tiempo_turno',
            field=models.DurationField(help_text='Duración entre turnos. Ejemplo: 00:20:00 para 20 minutos'),
        ),
    ]
