# Generated by Django 5.2.3 on 2025-11-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_medico_localidad'),
        ('cuenta', '0006_alter_horariotrabajo_tiempo_turno'),
    ]

    operations = [
    ]
