# Generated by Django 5.2.6 on 2025-09-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0006_usuariopersonalizado_num_dni_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariopersonalizado',
            old_name='num_dni',
            new_name='numero_dni',
        ),
    ]
