# Generated by Django 5.2.6 on 2025-11-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_merge_20251125_1529'),
        ('cuenta', '0006_alter_horariotrabajo_tiempo_turno'),
    ]

    operations = [
    ]
