# Generated by Django 5.2.3 on 2025-11-26 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_merge_20251125_1529'),
        ('cuenta', '0007_merge_20251125_1602'),
    ]

    operations = [
    ]
