# Generated by Django 5.1.1 on 2025-09-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0007_rename_num_dni_usuariopersonalizado_numero_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo_cuenta',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('medico', 'Medico')], default='Cliente', max_length=14),
        ),
    ]
