# Generated by Django 5.1.1 on 2025-10-07 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0008_alter_usuariopersonalizado_tipo_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo_cuenta',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Medico')], default='paciente', max_length=14),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('medico-clinico', 'Medico clinico'), ('traumatologo', 'Traumatologo'), ('dentista', 'Dentista')], default='medico-clinico', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], default='', max_length=200, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tiempo_turno', models.DurationField(help_text='Duración entre turnos. Ejemplo: 00:20:00 para 20 minutos')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='cuenta.lugartrabajo')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='cuenta.medico')),
            ],
            options={
                'ordering': ['lugar', 'dia', 'hora_inicio'],
                'unique_together': {('medico', 'lugar', 'dia', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
