# Generated by Django 5.2.3 on 2025-11-26 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0009_remove_medico_localidad_lugartrabajo_localidad'),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugartrabajo',
            name='localidad',
        ),
        migrations.AddField(
            model_name='medico',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='principal.localidad'),
        ),
    ]
