# Generated by Django 5.1.1 on 2025-10-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0010_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
