# Generated by Django 5.1.1 on 2025-10-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0011_remove_paciente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
