# Generated by Django 5.1.1 on 2025-10-28 19:35

import cuenta.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0012_alter_usuariopersonalizado_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugartrabajo',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='cuenta.medico'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='foto_dni',
            field=models.ImageField(blank=True, null=True, upload_to=cuenta.models.ruta_dni),
        ),
    ]
