# Generated by Django 5.1.1 on 2025-11-03 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0013_lugartrabajo_medico_and_more'),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='gobierno_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.gobiernolocal'),
        ),
        migrations.AddField(
            model_name='medico',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.localidad'),
        ),
    ]
