# Generated by Django 5.1.1 on 2025-11-11 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0014_medico_gobierno_local_medico_localidad'),
        ('principal', '0002_alter_gobiernolocal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='gobierno_local',
        ),
        migrations.AlterField(
            model_name='medico',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='principal.localidad'),
        ),
    ]
