# Generated by Django 5.1.1 on 2025-11-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0015_remove_medico_gobierno_local_alter_medico_localidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='localidad',
        ),
    ]
