# Generated by Django 5.2.6 on 2025-11-28 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_indec', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True, verbose_name='ID INDEC')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'principal_provincia',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_indec', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True, verbose_name='ID INDEC')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='principal.provincia')),
            ],
            options={
                'db_table': 'principal_departamento',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'provincia')},
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_indec', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True, verbose_name='ID INDEC')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='principal.departamento')),
            ],
            options={
                'db_table': 'principal_localidad',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'departamento')},
            },
        ),
    ]
