# Generated by Django 5.1.1 on 2025-11-11 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0015_remove_medico_gobierno_local_alter_medico_localidad'),
        ('principal', '0002_alter_gobiernolocal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_indec', models.CharField(default='Brandsen', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='ID INDEC')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'principal_departamento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_indec', models.CharField(default='Buenos aires', max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='ID INDEC')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'principal_provincia',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='localidad',
            name='id_indec',
            field=models.CharField(default='Coronel Brandsen', max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='ID INDEC'),
        ),
        migrations.AlterModelTable(
            name='localidad',
            table='principal_localidad',
        ),
        migrations.AddField(
            model_name='localidad',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='principal.departamento'),
        ),
        migrations.AlterUniqueTogether(
            name='localidad',
            unique_together={('nombre', 'departamento')},
        ),
        migrations.AddField(
            model_name='departamento',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='principal.provincia'),
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='gobierno_local',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='id',
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nombre', 'provincia')},
        ),
        migrations.DeleteModel(
            name='GobiernoLocal',
        ),
    ]
