# Generated by Django 5.1.1 on 2025-11-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_departamento_provincia_alter_localidad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='id_indec',
            field=models.CharField(default='Buenos Aires', max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='ID INDEC'),
        ),
    ]
