# Generated by Django 5.1.1 on 2025-11-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_provincia_id_indec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='id_indec',
            field=models.CharField(default='Jeppener', max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='ID INDEC'),
        ),
    ]
